"""ver0.1.1 photos/quality/daily fields

Revision ID: 93d342db7f58
Revises: ac419ff2d045
Create Date: 2026-07-23 07:14:55.138850
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '93d342db7f58'
down_revision: Union[str, None] = 'ac419ff2d045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_report_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['daily_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_report_photos_report_id'), 'daily_report_photos', ['report_id'], unique=False)
    op.add_column('daily_reports', sa.Column('place', sa.String(length=200), nullable=True))
    op.add_column('daily_reports', sa.Column('crew', sa.String(length=64), nullable=True))
    op.add_column('daily_reports', sa.Column('plan_workers', sa.Integer(), nullable=True))
    op.add_column('daily_reports', sa.Column('actual_workers', sa.Integer(), nullable=True))
    op.add_column('daily_reports', sa.Column('process', sa.String(length=200), nullable=True))
    op.add_column('daily_reports', sa.Column('materials', sa.Text(), nullable=True))
    op.add_column('daily_reports', sa.Column('tools', sa.Text(), nullable=True))
    op.add_column('daily_reports', sa.Column('vehicles', sa.Text(), nullable=True))
    op.add_column('daily_reports', sa.Column('hazard', sa.Text(), nullable=True))
    op.add_column('daily_reports', sa.Column('safety_check', sa.String(length=64), nullable=True))
    op.add_column('daily_reports', sa.Column('quality_check', sa.Text(), nullable=True))
    op.add_column('daily_reports', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('daily_reports', sa.Column('checker_id', sa.Integer(), nullable=True))
    op.add_column('daily_reports', sa.Column('approver_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'daily_reports', 'users', ['checker_id'], ['id'])
    op.create_foreign_key(None, 'daily_reports', 'users', ['approver_id'], ['id'])
    op.add_column('photos', sa.Column('photo_no', sa.String(length=32), nullable=True))
    op.add_column('photos', sa.Column('place', sa.String(length=200), nullable=True))
    op.add_column('photos', sa.Column('tags', sa.Text(), nullable=True))
    op.add_column('photos', sa.Column('favorite', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('quality_checks', sa.Column('inspect_item', sa.String(length=200), nullable=True))
    op.add_column('quality_checks', sa.Column('process', sa.String(length=120), nullable=True))
    op.add_column('quality_checks', sa.Column('judge', sa.String(length=16), nullable=False, server_default='未判定'))
    op.add_column('quality_checks', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('quality_checks', sa.Column('worker_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'quality_checks', 'users', ['worker_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quality_checks', type_='foreignkey')
    op.drop_column('quality_checks', 'worker_id')
    op.drop_column('quality_checks', 'due_date')
    op.drop_column('quality_checks', 'judge')
    op.drop_column('quality_checks', 'process')
    op.drop_column('quality_checks', 'inspect_item')
    op.drop_column('photos', 'favorite')
    op.drop_column('photos', 'tags')
    op.drop_column('photos', 'place')
    op.drop_column('photos', 'photo_no')
    op.drop_constraint(None, 'daily_reports', type_='foreignkey')
    op.drop_constraint(None, 'daily_reports', type_='foreignkey')
    op.drop_column('daily_reports', 'approver_id')
    op.drop_column('daily_reports', 'checker_id')
    op.drop_column('daily_reports', 'note')
    op.drop_column('daily_reports', 'quality_check')
    op.drop_column('daily_reports', 'safety_check')
    op.drop_column('daily_reports', 'hazard')
    op.drop_column('daily_reports', 'vehicles')
    op.drop_column('daily_reports', 'tools')
    op.drop_column('daily_reports', 'materials')
    op.drop_column('daily_reports', 'process')
    op.drop_column('daily_reports', 'actual_workers')
    op.drop_column('daily_reports', 'plan_workers')
    op.drop_column('daily_reports', 'crew')
    op.drop_column('daily_reports', 'place')
    op.drop_index(op.f('ix_daily_report_photos_report_id'), table_name='daily_report_photos')
    op.drop_table('daily_report_photos')
    # ### end Alembic commands ###
